import type { MenuResponse } from './types'

// Menu content is restaurant data, not UI copy, so it stays in Portuguese and
// is not translated. When a backend arrives this file is the only thing that
// goes away: `api.ts` keeps the same shape.
export const MOCK_MENU: MenuResponse = {
  venue: {
    venueSlug: 'cantina-do-porto',
    name: 'Cantina do Porto',
    tagline: 'Cozinha de mercado, massas frescas e vinho em taça',
    emoji: '🍝',
    serviceFeeRate: 0.1,
    currency: 'BRL',
    locale: 'pt-BR',
    tables: [
      { tableId: '7', label: 'Mesa 7', seats: 2 },
      { tableId: '12', label: 'Mesa 12', seats: 4 },
      { tableId: '15', label: 'Mesa 15', seats: 6 },
      { tableId: 'varanda-3', label: 'Varanda 3', seats: 4 },
    ],
  },
  categories: [
    { categoryId: 'entradas', name: 'Entradas', emoji: '🥖' },
    { categoryId: 'massas', name: 'Massas', emoji: '🍝' },
    { categoryId: 'principais', name: 'Principais', emoji: '🥩' },
    { categoryId: 'bebidas', name: 'Bebidas', emoji: '🍷' },
    { categoryId: 'sobremesas', name: 'Sobremesas', emoji: '🍰' },
  ],
  items: [
    {
      itemId: 'pao-na-chapa',
      categoryId: 'entradas',
      name: 'Pão de fermentação natural',
      description: 'Pão da casa na chapa, manteiga de ervas e flor de sal.',
      priceCents: 1800,
      emoji: '🥖',
      image: 'pao-na-chapa',
      tags: ['vegetarian'],
      available: true,
    },
    {
      itemId: 'bolinho-bacalhau',
      categoryId: 'entradas',
      name: 'Bolinho de bacalhau (6 un.)',
      description: 'Bacalhau desfiado, batata asterix e maionese de limão siciliano.',
      priceCents: 4200,
      emoji: '🐟',
      image: 'bolinho-bacalhau',
      tags: ['popular'],
      available: true,
    },
    {
      itemId: 'burrata',
      categoryId: 'entradas',
      name: 'Burrata com tomate assado',
      description: 'Burrata cremosa, tomate confitado, manjericão e azeite extravirgem.',
      priceCents: 5600,
      emoji: '🧀',
      image: 'burrata',
      tags: ['vegetarian', 'popular'],
      available: true,
    },
    {
      itemId: 'carpaccio',
      categoryId: 'entradas',
      name: 'Carpaccio de filé',
      description: 'Lâminas finas, alcaparras, rúcula e lascas de parmesão.',
      priceCents: 5200,
      emoji: '🥩',
      image: 'carpaccio',
      tags: [],
      available: false,
    },
    {
      itemId: 'cacio-e-pepe',
      categoryId: 'massas',
      name: 'Cacio e pepe',
      description: 'Espaguete fresco, pecorino romano e pimenta do reino moída na hora.',
      priceCents: 6800,
      emoji: '🧀',
      image: 'cacio-e-pepe',
      tags: ['vegetarian'],
      available: true,
    },
    {
      itemId: 'rague-costela',
      categoryId: 'massas',
      name: 'Pappardelle ao ragù de costela',
      description: 'Costela cozida por 8 horas, tomate San Marzano e parmesão.',
      priceCents: 8900,
      emoji: '🍝',
      image: 'rague-costela',
      tags: ['popular'],
      available: true,
    },
    {
      itemId: 'ravioli-ricota',
      categoryId: 'massas',
      name: 'Ravióli de ricota e espinafre',
      description: 'Massa verde recheada na hora, manteiga de sálvia e amêndoas.',
      priceCents: 7400,
      emoji: '🥬',
      image: 'ravioli-ricota',
      tags: ['vegetarian', 'new'],
      available: true,
    },
    {
      itemId: 'linguine-frutos',
      categoryId: 'massas',
      name: 'Linguine com frutos do mar',
      description: 'Camarão, lula e mexilhão ao molho de tomate levemente picante.',
      priceCents: 9800,
      emoji: '🦐',
      image: 'linguine-frutos',
      tags: ['spicy'],
      available: true,
    },
    {
      itemId: 'ancho',
      categoryId: 'principais',
      name: 'Bife ancho 300g',
      description: 'Grelhado na brasa, batata rústica e chimichurri da casa.',
      priceCents: 12900,
      emoji: '🥩',
      image: 'ancho',
      tags: ['popular', 'glutenFree'],
      available: true,
    },
    {
      itemId: 'peixe-do-dia',
      categoryId: 'principais',
      name: 'Peixe do dia',
      description: 'Filé grelhado, purê de mandioquinha e legumes salteados.',
      priceCents: 10900,
      emoji: '🐠',
      image: 'peixe-do-dia',
      tags: ['glutenFree'],
      available: true,
    },
    {
      itemId: 'risoto-cogumelos',
      categoryId: 'principais',
      name: 'Risoto de cogumelos',
      description: 'Arbóreo, mix de cogumelos frescos, parmesão e azeite trufado.',
      priceCents: 8600,
      emoji: '🍄',
      image: 'risoto-cogumelos',
      tags: ['vegetarian', 'glutenFree'],
      available: true,
    },
    {
      itemId: 'vinho-taca',
      categoryId: 'bebidas',
      name: 'Vinho tinto em taça',
      description: 'Malbec argentino, taça de 150ml.',
      priceCents: 3400,
      emoji: '🍷',
      image: 'vinho-taca',
      tags: ['popular'],
      available: true,
    },
    {
      itemId: 'chopp',
      categoryId: 'bebidas',
      name: 'Chopp pilsen 300ml',
      description: 'Puro malte, bem gelado, colarinho na medida.',
      priceCents: 1600,
      emoji: '🍺',
      image: 'chopp',
      tags: [],
      available: true,
    },
    {
      itemId: 'limonada',
      categoryId: 'bebidas',
      name: 'Limonada suíça',
      description: 'Limão batido com gelo e leite condensado.',
      priceCents: 1400,
      emoji: '🍋',
      image: 'limonada',
      tags: ['vegetarian'],
      available: true,
    },
    {
      itemId: 'agua',
      categoryId: 'bebidas',
      name: 'Água mineral 500ml',
      description: 'Com ou sem gás.',
      priceCents: 800,
      emoji: '💧',
      image: 'agua',
      tags: [],
      available: true,
    },
    {
      itemId: 'tiramisu',
      categoryId: 'sobremesas',
      name: 'Tiramisù',
      description: 'Mascarpone, café espresso e cacau em pó.',
      priceCents: 3200,
      emoji: '🍰',
      image: 'tiramisu',
      tags: ['popular', 'vegetarian'],
      available: true,
    },
    {
      itemId: 'pudim',
      categoryId: 'sobremesas',
      name: 'Pudim de leite',
      description: 'Receita da casa, calda de caramelo escuro.',
      priceCents: 2400,
      emoji: '🍮',
      image: 'pudim',
      tags: ['vegetarian', 'glutenFree'],
      available: true,
    },
    {
      itemId: 'petit-gateau',
      categoryId: 'sobremesas',
      name: 'Petit gâteau',
      description: 'Bolo quente de chocolate 70% com sorvete de creme.',
      priceCents: 3600,
      emoji: '🍫',
      image: 'petit-gateau',
      tags: ['vegetarian'],
      available: true,
    },
  ],
}
